on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.12"
          cache: "pip"
      - run: "python -m pip install --upgrade pip"
      - run: "pip install -r requirements.txt"
      - run: "pip install black pylint"
      - run: "black --check ."
      - run: "pylint *.py --disable=C"
      - run: "python -m unittest"

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: "redhat-actions/buildah-build@v2"
        id: "build"
        with:
          image: "pygreeter"
          tags: "latest ${{ github.sha }}"
          containerfiles: "./Containerfile"
      - uses: "redhat-actions/push-to-registry@v2"
        if: "github.ref == 'refs/heads/main'"
        env:
          IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"
        with:
          image: "${{ steps.build.outputs.image }}"
          tags: "${{ steps.build.outputs.tags }}"
          registry: "${{ env.IMAGE_REGISTRY }}"
          username: "$"
          password: "${{ secrets.GITHUB_TOKEN }}"
